### ISSUE TITLE
referencing structure by QbKey

### ISSUE THREAD

**Issue by donnaken15** [adituv/qbscript#1]
I'm sure this thing still doesn't matter to you now, but if you still want to assist, I'm trying to figure out how to use a structure in a PAK file that equals the name of a QbKey in a QbScript. So, for example, calling a value within `current_boss`, when `current_boss = Boss_TomMorello_Props`.
I tried doing things like `%deth_icon_texture = *current_boss.character_icon`

**Comment by donnaken15** [comment]
oh, apparently what i'm trying to do kind of works now but it's not friendly with outside script changes, like the boss time

**Comment by adituv** [comment]
As you might have guessed, I haven't looked at this in years.  I unfortunately can't really help with QB scripts any more; all I can suggest is to look through the original game scripts in the fork of Queen Bee that has the script decompiler baked in.

**Comment by donnaken15** [comment]
:/
